version: 2

sources:
    - name: External_table_source
      database: raw
      schema: public
      tables:
          - name: external_customer_with_partition
            columns:
            - name: customer_id
              tests:
              - unique
              - warn_if_null_with_insert
          - name: external_order_partion
            columns:
            - name: order_id
              tests:
              #- unique
              - warn_if_null_with_insert                
          
          
          
models:
  - name: stg_customers_using_external
    columns:
      - name: customer_id
        tests:
          #- unique
          - warn_if_null_with_insert
          - datatype_check
  - name: stg_orders_using_external
    columns:
      - name: order_id
        tests:
          #- unique
          - warn_if_null_with_insert        
         
                           
